networks:
  irisnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ${iris_container_name}
    hostname: ${iris_container_name}
    ports:
      - 12772:1972
      - 12775:52773
      - 53773
    command: --check-caps false --key /key/iris.key
    # environment:
    #   - ISC_DATA_DIRECTORY=/irisdata
    volumes:
      - ./data:/data
      - ./key:/key
      # - ./irisdata:/irisdata
    networks:
      irisnetwork:
        ipv4_address: 172.0.0.10
  webgateway:
    hostname: ${web_container_name}
    container_name: ${web_container_name}
    depends_on:
      - iris
    # image: intersystems/webgateway-arm64:2022.1.0.209.0
    image: containers.intersystems.com/intersystems/webgateway-arm64:2022.1.0.209.0
    ports:
    - ${web_port_https}:443
    - ${web_port_http}:80
    environment:
      - ISC_DATA_DIRECTORY=/webgateway
      - IRIS_USER=CSPsystem
      - IRIS_PASSWORD=SYS
    networks:
      irisnetwork:
        ipv4_address: 172.0.0.200
    volumes:
      - "./webgateway:/webgateway"
  mysql: 
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    init: true
    container_name: formation-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  # ftpd_server:
  #   image: stilliard/pure-ftpd
  #   container_name: pure-ftpd
  #   ports:
  #     - 21:21
  #     - "30000-30009:30000-30009"
  #   volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
  #     - ./data:/home/username/
  #     # - ./data/ftp:/data
  #     - ./data/passwd:/etc/pure-ftpd/passwd
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# or ssl/tls with Let's Encrypt (cert and key as two files)
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
#     environment:
#       PUBLICHOST: "localhost"
#       FTP_USER_NAME: username
#       FTP_USER_PASS: mypass
#       FTP_USER_HOME: /home/username
# # also for ssl/tls:
# #      ADDED_FLAGS: "--tls=2"
#     restart: always




