groups:
- name: isc_reserved
  rules:
  - alert: iris_system_alerts
    annotations:
      description: 'WARNING: Removing this rule will disable the handling of InterSystems
        IRIS System Monitor text alerts!'
    expr: (idelta(iris_system_alerts_log[5m]) != 0) or (iris_system_alerts_new > 0)
- name: "1"
  rules:
  - alert: CPU-90
    annotations:
      description: CPU > 90%
    expr: iris_cpu_usage{cluster="1"} > 90
    labels:
      severity: critical
  - alert: cache-efficiency-too-low
    annotations:
      description: cache efficiency too low
    expr: iris_cache_efficiency{cluster="1"} < 2000
    labels:
      severity: warning
- name: "2"
  rules: []

