version: '3.2'
services:
  db-migration:
    build: .
    environment:
      PGUSER: ${KONG_PG_USER:-iam}
    volumes:
      - 'pgdata:/var/lib/postgresql/9.6/data'
      - 'pgdata14:/var/lib/postgresql/14/data'
    stdin_open: true
volumes:
  pgdata:
  pgdata14:
